import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from '../Components/Navbar/page'
import App from "next/app";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <App/> */}
        <Navbar/>
        <div className="p-16 w-full bg-gradient-to-br from-indigo-900 via-purple-900 to-indigo-800">
            
        {children}
        </div>
      </body>
    </html>
  );
}
